version: '3.9'

services:
  order-service:
    image: order-service:latest
    ports:
      - 8040:8040
    networks:
      - app-network
  inventory-service:
    image: 'inventory-service:latest'
    build:
      context: .
    container_name: inventory-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 8010:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network

networks:
  app-network:
    external: true